format = """
[](#a3aed2)\
[](bg:#a3aed2 fg:#090c0c)\
[ğŸ­¬](bg:#769ff0 fg:#a3aed2)\
$directory\
[ğŸ­¬](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[ğŸ­¬](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$golang\
$php\
[ğŸ­¬](fg:#212736 bg:#1d2230)\
[ğŸ­¬ ](fg:#1d2230)\
\n$character"""
right_format = """
[ğŸ­®](fg:#1d2230)\
$cmd_duration\
$time\
"""

[directory]
style = "fg:#000000 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
"ãƒ€ã‚¦ãƒ³ãƒ­ãƒ¼ãƒ‰" = "ï€™ "
"ãƒ†ãƒ³ãƒ—ãƒ¬ãƒ¼ãƒˆ" = "ï‘º "
"ãƒ‡ã‚¹ã‚¯ãƒˆãƒƒãƒ—" = "ó°‡„ "
"ãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆ" = "ó°ˆ™ "
"ãƒ“ãƒ‡ã‚ª" = "ó°ˆ« "
"å…¬é–‹" = "ï‡¡ "
"ç”»åƒ" = "ï€¾ "
"éŸ³æ¥½" = "ï€ "
"~" = "ï€• "


[git_branch]
symbol = "ï˜"
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[rust]
symbol = "î¨"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = "î˜§"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = "î˜ˆ"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ ïº $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[cmd_duration]
disabled = false
style = "bg:#1d2230"
format = '[[ $duration ](fg:#a0a9cb bg:#1d2230)]($style)'
min_time = 1

[nodejs]
disabled = true
